/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class App {

    public static void main(String[] args) {
        Mobile mobileA = new Mobile("fantszIPhone", "Blue", "IPhone7s");
        mobileA.callout("greetings from fantszIphone7s");
        Mobile mobileB = new Mobile("fantszAndroid", "Blue", "AndroidS9");
        mobileB.callout("greetings from fantszAndroidS9");
    }
}
