/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class App {

    public static void main(String[] args) {
        IPhone mobileA = new IPhone("fantszIPhone", "Blue", "IPhone7s");
        mobileA.callout("Greetings from fantszIphone7s");
        mobileA.basicInfo();

        System.out.println("----------------------------------------------");
        Android mobileB = new Android("fantszAndroid", "White", "AndroidS9");
        mobileB.callout("Greetings from fantszAndroidS9");
        mobileB.basicInfo();

        System.out.println("----------------------------------------------");
        IPhone iPhone = new IPhone("fantszIPhone", "Blue", "IPhone7s");
        Person fantsz = new Person(iPhone, "fantsz");
        fantsz.callout("Length of this line exceed 30. So message cannot be sent");

        System.out.println("----------------------------------------------");
        Android android = new Android("fantszAndroid", "White", "AndroidS9");
        Person fantszching = new Person(mobileB, "fantszching");
        fantszching.callout("Length of this line exceed 30. So message cannot be sent");
    }
}
